version: '3'
services:
  front:
    image: node:16.13.1
    container_name: front
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /usr/src/app
    volumes:
      - ./front:/usr/src/app
      - front-volumes:/usr/src/app/public
    command: ./yarn.sh
    ports:
      - "3000:3000"
    networks:
      todo_network:
        ipv4_address: 172.30.0.2
    depends_on:
      - node
      - mysql
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - front-volumes:/usr/src/app/public
    ports:
      - 3001:80
    networks:
      todo_network:
        ipv4_address: 172.30.0.3
    depends_on:
      - node
      - mysql
  node:
    image: node:16.13.1
    container_name: node
    working_dir: /usr/src/app
    command: ./yarn.sh
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3002:8080"
    networks:
      todo_network:
        ipv4_address: 172.30.0.4
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64 # M1mac対応
    image: mysql:5.7
    container_name: mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/my.conf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3003:3306"
    networks:
      todo_network:
        ipv4_address: 172.30.0.5
networks:
  todo_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
volumes:
  front-volumes: